import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Poppins({subsets: ["latin"],weight: ["400", "500", "600", "700", "900"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-zinc-100"}>
				<Providers>{children}</Providers>	
			</body>
    </html>
  );
}
